import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import backgroundImg from "@/../public/img/bg-bottom-bar.png";
import Image from "next/image";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import theme from "@/theme";
import { ThemeProvider } from "@mui/material/styles";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className} style={{ background: "#093545" }}>
                <AppRouterCacheProvider>
                    <ThemeProvider theme={theme}>
                        <>
                            {children}
                            <div
                                style={{
                                    position: "absolute",
                                    bottom: 0,
                                    width: "100vw",
                                    zIndex: -1,
                                }}>
                                <Image
                                    src={backgroundImg}
                                    alt="Background"
                                    style={{ width: "100%" }}
                                />
                            </div>
                        </>
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
