#/bin/sh

# exit when any command fails
set -e

DEFAULT_APPCODE_EXECUTOR_IMAGE=""
DEFAULT_FILES_IMAGE=""
DEFAULT_NODEDEPS_IMAGE=""

if [ -z "$DOCKER_PROJECT_PATH" ]; then
    APPCODE_EXECUTOR_IMAGE=$DEFAULT_APPCODE_EXECUTOR_IMAGE
else
    APPCODE_EXECUTOR_IMAGE="$DOCKER_PROJECT_PATH"
fi

COMMON_ARGS=" --build-arg RELEASE_VERSION=$RELEASE_VERSION --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg COMMIT_HASH=$CI_COMMIT_SHA "

docker pull $DOCKER_PROJECT_PATH || true

docker tag $DOCKER_PROJECT_PATH movies-demo-2 || true
